
- name: First interaction
  uses: actions/first-interaction@v1.3.0
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue-message: "Obrigado por abrir sua primeira issue!"
    pr-message: "Obrigado pelo seu primeiro pull request!"


