name: CI Flutter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'

      - name: Instalar dependências
        run: flutter pub get

      - name: Verificar formatação do código
        run: dart format --check .

      - name: Analisar o código
        run: flutter analyze

      - name: Rodar os testes
        run: flutter test
      
      
  
